// Petfinder Official Breed Dictionary
// Source: Petfinder API v2 - https://www.petfinder.com/developers/v2/docs/
// Last updated: 2024

export const PETFINDER_BREEDS = {
  Dog: [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alaskan Malamute",
    "American Bulldog",
    "American Bully",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd",
    "Appenzell Mountain Dog",
    "Australian Cattle Dog / Blue Heeler",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Shepherd / Laekenois",
    "Belgian Shepherd / Malinois",
    "Belgian Shepherd / Sheepdog",
    "Belgian Shepherd / Tervuren",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Black Labrador Retriever",
    "Black Mouth Cur",
    "Black Russian Terrier",
    "Bloodhound",
    "Blue Lacy",
    "Bluetick Coonhound",
    "Boerboel",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Briard",
    "Brittany Spaniel",
    "Brussels Griffon",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Canaan Dog",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Carolina Dog",
    "Catahoula Leopard Dog",
    "Cattle Dog",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested Dog",
    "Chinese Shar-Pei",
    "Chinook",
    "Chocolate Labrador Retriever",
    "Chow Chow",
    "Cirneco dell'Etna",
    "Clumber Spaniel",
    "Cockapoo",
    "Cocker Spaniel",
    "Collie",
    "Coonhound",
    "Corgi",
    "Coton de Tulear",
    "Curly-Coated Retriever",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogue de Bordeaux",
    "Dutch Shepherd",
    "English Bulldog",
    "English Cocker Spaniel",
    "English Coonhound",
    "English Foxhound",
    "English Pointer",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "Entlebucher",
    "Eskimo Dog",
    "Feist",
    "Field Spaniel",
    "Fila Brasileiro",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "Foxhound",
    "French Bulldog",
    "Galgo Spanish Greyhound",
    "German Pinscher",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Spitz",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Goldendoodle",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Hamiltonstovare",
    "Harrier",
    "Havanese",
    "Hound",
    "Hovawart",
    "Husky",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Jindo",
    "Kai Dog",
    "Karelian Bear Dog",
    "Keeshond",
    "Kerry Blue Terrier",
    "Kishu",
    "Komondor",
    "Kuvasz",
    "Kyi Leo",
    "Labradoodle",
    "Labrador Retriever",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Leonberger",
    "Lhasa Apso",
    "Lowchen",
    "Maltese",
    "Manchester Terrier",
    "Maremma Sheepdog",
    "Mastiff",
    "McNab",
    "Miniature Bull Terrier",
    "Miniature Dachshund",
    "Miniature Pinscher",
    "Miniature Poodle",
    "Miniature Schnauzer",
    "Mixed Breed",
    "Mountain Cur",
    "Mountain Dog",
    "Munsterlander",
    "Neapolitan Mastiff",
    "New Guinea Singing Dog",
    "Newfoundland Dog",
    "Norfolk Terrier",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Parson Russell Terrier",
    "Patterdale Terrier / Fell Terrier",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Peruvian Inca Orchid",
    "Petit Basset Griffon Vendeen",
    "Pharaoh Hound",
    "Pit Bull Terrier",
    "Plott Hound",
    "Pointer",
    "Polish Lowland Sheepdog",
    "Pomeranian",
    "Poodle",
    "Portuguese Podengo",
    "Portuguese Water Dog",
    "Presa Canario",
    "Pug",
    "Puli",
    "Pumi",
    "Pyrenean Shepherd",
    "Rat Terrier",
    "Redbone Coonhound",
    "Retriever",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Rough Collie",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Sarplaninac",
    "Schipperke",
    "Schnauzer",
    "Schnoodle",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Setter",
    "Shar-Pei",
    "Sheep Dog",
    "Sheepadoodle",
    "Shepherd",
    "Shetland Sheepdog / Sheltie",
    "Shiba Inu",
    "Shih Tzu",
    "Shih Poo",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Smooth Collie",
    "Smooth Fox Terrier",
    "Soft Coated Wheaten Terrier",
    "Spaniel",
    "Spanish Mastiff",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Spitz",
    "Staffordshire Bull Terrier",
    "Standard Poodle",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Swedish Vallhund",
    "Tennessee Treeing Brindle",
    "Terrier",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Tosa Inu",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Toy Poodle",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier / Westie",
    "Wheaten Terrier",
    "Whippet",
    "White German Shepherd",
    "Wire Fox Terrier",
    "Wirehaired Dachshund",
    "Wirehaired Pointing Griffon",
    "Wirehaired Terrier",
    "Xoloitzcuintli / Mexican Hairless",
    "Yellow Labrador Retriever",
    "Yorkshire Terrier"
  ],
  
  Cat: [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Applehead Siamese",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Calico",
    "Canadian Hairless",
    "Chartreux",
    "Chausie",
    "Chinchilla",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Dilute Calico",
    "Dilute Tortoiseshell",
    "Domestic Long Hair",
    "Domestic Medium Hair",
    "Domestic Short Hair",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Extra-Toes Cat / Hemingway Polydactyl",
    "Havana",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Long Hair",
    "Oriental Short Hair",
    "Oriental Tabby",
    "Persian",
    "Pixiebob",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese",
    "Siberian",
    "Silver",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx / Hairless Cat",
    "Tabby",
    "Tiger",
    "Tonkinese",
    "Torbie",
    "Tortoiseshell",
    "Turkish Angora",
    "Turkish Van",
    "Tuxedo",
    "York Chocolate"
  ],
  
  Rabbit: [
    "American",
    "American Fuzzy Lop",
    "American Sable",
    "Angora Rabbit",
    "Belgian Hare",
    "Beveren",
    "Britannia Petite",
    "Bunny Rabbit",
    "Californian",
    "Champagne D'Argent",
    "Checkered Giant",
    "Chinchilla",
    "Cinnamon",
    "Crème D'Argent",
    "Dutch",
    "Dwarf",
    "Dwarf Eared",
    "English Angora",
    "English Lop",
    "English Spot",
    "Flemish Giant",
    "Florida White",
    "French Angora",
    "French Lop",
    "Giant Angora",
    "Harlequin",
    "Havana",
    "Himalayan",
    "Holland Lop",
    "Hotot",
    "Jersey Wooly",
    "Lilac",
    "Lionhead",
    "Lop Eared",
    "Mini Lop",
    "Mini Rex",
    "Mini Satin",
    "Netherland Dwarf",
    "New Zealand",
    "Palomino",
    "Polish",
    "Rex",
    "Rhinelander",
    "Satin",
    "Satin Angora",
    "Silver",
    "Silver Fox",
    "Silver Marten",
    "Standard Chinchilla",
    "Tan"
  ],
  
  "Small & Furry": [
    "Abyssinian",
    "Chinchilla",
    "Degu",
    "Ferret",
    "Gerbil",
    "Guinea Pig",
    "Hamster",
    "Hedgehog",
    "Mouse",
    "Peruvian",
    "Prairie Dog",
    "Rat",
    "Rex",
    "Short-Haired",
    "Silkie / Sheltie",
    "Skinny Pig",
    "Sugar Glider",
    "Teddy"
  ],
  
  Horse: [
    "Appaloosa",
    "Arabian",
    "Belgian",
    "Clydesdale",
    "Curly Horse",
    "Donkey / Mule",
    "Draft",
    "Gaited",
    "Grade",
    "Lipizzan",
    "Miniature Horse",
    "Missouri Foxtrotter",
    "Morgan",
    "Mustang",
    "Paint / Pinto",
    "Palomino",
    "Paso Fino",
    "Percheron",
    "Peruvian Paso",
    "Pony",
    "Quarterhorse",
    "Rocky Mountain Horse",
    "Saddlebred",
    "Shetland Pony",
    "Standardbred",
    "Tennessee Walker",
    "Thoroughbred",
    "Warmblood"
  ],
  
  Bird: [
    "African Grey",
    "Amazon",
    "Brotogeris",
    "Budgie / Budgerigar",
    "Caique",
    "Canary",
    "Chicken",
    "Cockatiel",
    "Cockatoo",
    "Conure",
    "Dove",
    "Duck",
    "Eclectus",
    "Emu",
    "Finch",
    "Goose",
    "Guinea Fowl",
    "Kakariki",
    "Lory / Lorikeet",
    "Lovebird",
    "Macaw",
    "Mynah",
    "Ostrich",
    "Parakeet (Other)",
    "Parrot (Other)",
    "Parrotlet",
    "Peacock / Peahen",
    "Pheasant",
    "Pigeon",
    "Pionus",
    "Poicephalus / Senegal",
    "Quaker Parakeet",
    "Ringneck / Psittacula",
    "Rosella",
    "Swan",
    "Toucan",
    "Turkey"
  ],
  
  "Scales, Fins & Other": [
    "Asian Box Turtle",
    "Ball Python",
    "Bearded Dragon",
    "Boa",
    "Boa Constrictor",
    "Box Turtle",
    "Bull Frog",
    "Chameleon",
    "Corn Snake / Rat Snake",
    "Dart Frog",
    "Eastern Box Turtle",
    "Fire Salamander",
    "Fire-Bellied Newt",
    "Fire-Bellied Toad",
    "Florida Box Turtle",
    "Freshwater Fish",
    "Frog",
    "Gecko",
    "Goldfish",
    "Gopher / Desert Tortoise",
    "Greek Tortoise",
    "Gulf Coast Box Turtle",
    "Hermit Crab",
    "Hermit's Crab",
    "Horned Frog",
    "Iguana",
    "King / California King Snake",
    "Koi",
    "Leopard Frog",
    "Leopard Gecko",
    "Lizard",
    "Marine Fish / Saltwater Fish",
    "Milk Snake",
    "Monitor",
    "Mud Turtle",
    "Musk Turtle",
    "Newt",
    "Ornamental Box Turtle",
    "Pacman Frog",
    "Painted Turtle",
    "Python",
    "Red Foot Tortoise",
    "Red-Eared Slider",
    "Russian Tortoise",
    "Salamander",
    "Scorpion",
    "Sea Turtle",
    "Snapping Turtle",
    "Snake",
    "Soft Shell Turtle",
    "Spotted Turtle",
    "Sulcata Tortoise",
    "Tarantula",
    "Three-Toed Box Turtle",
    "Tiger Salamander",
    "Toad",
    "Tokay Gecko",
    "Tortoise",
    "Tree Frog",
    "Turtle",
    "Uromastyx",
    "Water Dragon",
    "Yellow-Bellied Slider"
  ],
  
  Barnyard: [
    "Alpaca",
    "Cow",
    "Donkey",
    "Goat",
    "Llama",
    "Pig",
    "Sheep"
  ]
} as const;

// Type for breed lookup
export type PetfinderBreedsByType = typeof PETFINDER_BREEDS;

// Helper to get breeds for a specific type
export function getBreedsForType(type: keyof typeof PETFINDER_BREEDS): readonly string[] {
  return PETFINDER_BREEDS[type] || [];
}

// Helper to validate if a breed is valid for a type
export function isValidBreed(type: keyof typeof PETFINDER_BREEDS, breed: string): boolean {
  const breeds = PETFINDER_BREEDS[type];
  if (!breeds) return false;
  return breeds.includes(breed as any);
}

// Map internal species to Petfinder type
export function mapSpeciesToPetfinderType(species: string): keyof typeof PETFINDER_BREEDS | null {
  const normalizedSpecies = species.toLowerCase().trim();
  
  const mappings: Record<string, keyof typeof PETFINDER_BREEDS> = {
    'dog': 'Dog',
    'dogs': 'Dog',
    'puppy': 'Dog',
    'puppies': 'Dog',
    'cat': 'Cat',
    'cats': 'Cat',
    'kitten': 'Cat',
    'kittens': 'Cat',
    'rabbit': 'Rabbit',
    'rabbits': 'Rabbit',
    'bunny': 'Rabbit',
    'bunnies': 'Rabbit',
    'guinea pig': 'Small & Furry',
    'hamster': 'Small & Furry',
    'ferret': 'Small & Furry',
    'gerbil': 'Small & Furry',
    'mouse': 'Small & Furry',
    'rat': 'Small & Furry',
    'chinchilla': 'Small & Furry',
    'hedgehog': 'Small & Furry',
    'sugar glider': 'Small & Furry',
    'small animal': 'Small & Furry',
    'small & furry': 'Small & Furry',
    'horse': 'Horse',
    'horses': 'Horse',
    'pony': 'Horse',
    'donkey': 'Horse',
    'mule': 'Horse',
    'bird': 'Bird',
    'birds': 'Bird',
    'parrot': 'Bird',
    'parakeet': 'Bird',
    'cockatiel': 'Bird',
    'chicken': 'Bird',
    'duck': 'Bird',
    'reptile': 'Scales, Fins & Other',
    'snake': 'Scales, Fins & Other',
    'lizard': 'Scales, Fins & Other',
    'turtle': 'Scales, Fins & Other',
    'tortoise': 'Scales, Fins & Other',
    'frog': 'Scales, Fins & Other',
    'fish': 'Scales, Fins & Other',
    'scales, fins & other': 'Scales, Fins & Other',
    'farm animal': 'Barnyard',
    'barnyard': 'Barnyard',
    'goat': 'Barnyard',
    'pig': 'Barnyard',
    'sheep': 'Barnyard',
    'cow': 'Barnyard',
    'llama': 'Barnyard',
    'alpaca': 'Barnyard',
  };
  
  return mappings[normalizedSpecies] || null;
}
